services:
  db:
    image: ankane/pgvector:latest
    container_name: pgvector-db-crm-manh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    build: 
      context: .
      dockerfile: docker/odoo/Dockerfile
    image: odoo-image:19.0
    container_name: crm-manh
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
      - odoo_web_data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_password
    restart: unless-stopped

volumes:
  odoo_db_data:
  odoo_web_data: